### ISSUE TITLE
Server Fails to Start after Latest Update

### ISSUE THREAD

**Issue by MadSciSlack** [NyanMC/ChromaticArsenal#3]
Updated on my server to the latest version (1.14) of this mod, and I get this crash regarding the curios renderer:

A detailed walkthrough of the error, its code path and all known details is as follows:
[24.11 03:21:31] [Server] ---------------------------------------------------------------------------------------
[24.11 03:21:31] [Server] -- Head --
[24.11 03:21:31] [Server] Threadmain
[24.11 03:21:31] [Server] Suspected ModsNONE
[24.11 03:21:31] [Server] Stacktrace:
[24.11 03:21:31] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:1.{}
[24.11 03:21:31] [Server] -- MOD chromaticarsenal --
[24.11 03:21:31] [Server] Details:
[24.11 03:21:31] [Server] 	Caused by java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class com/chromanyan/chromaticarsenal/client/renderer/CuriosRenderers for invalid dist DEDICATED_SERVER
[24.11 03:21:31] [Server] 		at com.chromanyan.chromaticarsenal.ChromaticArsenal.<init>(ChromaticArsenal.java:59) ~[chromaticarsenal-1.19.2-1.14.0.jar%23359!/:1.14.{re:classloading,pl:runtimedistcleaner:A}
[24.11 03:21:31] [Server] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[24.11 03:21:31] [Server] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[24.11 03:21:31] [Server] 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[24.11 03:21:31] [Server] 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[24.11 03:21:31] [Server] 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[24.11 03:21:31] [Server] 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.5.jar%23557!/:?] {}
[24.11 03:21:31] [Server] 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.5.jar%23556!/:?] {}
[24.11 03:21:31] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[24.11 03:21:31] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[24.11 03:21:31] [Server] 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[24.11 03:21:31] [Server] 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[24.11 03:21:31] [Server] 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[24.11 03:21:31] [Server] 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[24.11 03:21:31] [Server] 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[24.11 03:21:31] [Server] 	Mod File/mods/chromaticarsenal-1.19.2-1.14.0.jar
[24.11 03:21:31] [Server] 	Failure messageChromatic Arsenal (chromaticarsenal) has failed to load correctly
[24.11 03:21:31] [Server] 		java.lang.BootstrapMethodErrorjava.lang.RuntimeException: Attempted to load class com/chromanyan/chromaticarsenal/client/renderer/CuriosRenderers for invalid dist DEDICATED_SERVER
[24.11 03:21:31] [Server] 	Mod Version1.14.0
[24.11 03:21:31] [Server] 	Mod Issue URLhttps://github.com/NyanMC/ChromaticArsenal/issues
[24.11 03:21:31] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class com/chromanyan/chromaticarsenal/client/renderer/CuriosRenderers for invalid dist DEDICATED_SERVER
[24.11 03:21:31] [Server] Stacktrace:
[24.11 03:21:31] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.5.jar%2367!/:1.{}
[24.11 03:21:31] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
[24.11 03:21:31] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
[24.11 03:21:31] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[24.11 03:21:31] [Server] 	at com.chromanyan.chromaticarsenal.ChromaticArsenal.<init>(ChromaticArsenal.java:59) ~[chromaticarsenal-1.19.2-1.14.0.jar%23359!/:1.14.{re:classloading,pl:runtimedistcleaner:A}
[24.11 03:21:31] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[24.11 03:21:31] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[24.11 03:21:31] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[24.11 03:21:31] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[24.11 03:21:31] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[24.11 03:21:31] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.5.jar%23557!/:?] {}
[24.11 03:21:31] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.3.5.jar%23556!/:?] {}
[24.11 03:21:31] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[24.11 03:21:31] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[24.11 03:21:31] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[24.11 03:21:31] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[24.11 03:21:31] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[24.11 03:21:31] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[24.11 03:21:31] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[24.11 03:21:31] [Server] -- System Details --
[24.11 03:21:31] [Server] Details:
[24.11 03:21:31] [Server] 	Minecraft Version1.19.2
[24.11 03:21:31] [Server] 	Minecraft Version ID1.19.2
[24.11 03:21:31] [Server] 	Operating SystemLinux (amd64) version 5.15.0-88-generic
[24.11 03:21:31] [Server] 	Java Version17.0.8, Oracle Corporation

Hopefully this is helpful.  I'll just roll-back the mod to the 1.13 release for now.

Cheers,

- Slack

**Comment by NyanMC** [comment]
oh no. i probably forgot to tag something with @OnlyIn or some other problem which involves not telling the class to only load clientside, i'll get right on this

**Comment by NyanMC** [comment]
shit i just accidentally pinged a random github user

**Comment by NyanMC** [comment]
(hopefully) fixed with 19815d8f894ccbad6abab54b3eef0f0ee932ac72. the release which fixes this crash is already up on modrinth and will be up on curseforge as soon as it gets approved, re-open this issue if the issue persists on version 1.14.1

**Comment by MadSciSlack** [comment]
Dang, you work fast. Good stuff, and a good mod.  It fits into various packs and themes pretty easily.
